# Generated by Django 3.1.6 on 2021-02-09 16:37

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=account.models.get_upload_path, verbose_name='Profile Photo')),
                ('job', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job')),
                ('Education', models.CharField(blank=True, max_length=50, null=True, verbose_name='Education')),
                ('Location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('Skills', models.CharField(blank=True, max_length=50, null=True, verbose_name='Skills')),
                ('Notes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Notes')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_at')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('category', models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200, null=True, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('tags', models.ManyToManyField(to='account.Tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=50, null=True, verbose_name='status')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='note')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='Customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Ivrepresentative',
            fields=[
                ('companycode', models.CharField(choices=[('0001', 'OTC')], db_column='CompanyCode', max_length=4, verbose_name='Company')),
                ('representativecode', models.CharField(db_column='representativeCode', max_length=6, primary_key=True, serialize=False, verbose_name='Code')),
                ('representativenamea', models.CharField(blank=True, db_column='representativeNameA', max_length=50, null=True, verbose_name='Arabic Name')),
                ('representativenamee', models.CharField(blank=True, db_column='representativeNameE', max_length=50, null=True, verbose_name='English Name')),
            ],
            options={
                'db_table': 'Ivrepresentative',
                'managed': True,
                'unique_together': {('companycode', 'representativecode')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, default=account.models.increment_invoice_number, max_length=500, null=True)),
                ('invoice_date', models.DateField(auto_now=True, verbose_name='invoice date')),
                ('order', models.ManyToManyField(to='account.Order', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('companycode', models.CharField(choices=[('0001', 'OTC')], db_column='CompanyCode', max_length=4, verbose_name='Company')),
                ('branchcode', models.CharField(db_column='BranchCode', max_length=4, primary_key=True, serialize=False, verbose_name='Code')),
                ('branchnamea', models.CharField(blank=True, db_column='BranchNameA', max_length=50, null=True, verbose_name='Arabic Name')),
                ('branchnamee', models.CharField(blank=True, db_column='BranchNameE', max_length=50, null=True, verbose_name='English Name')),
                ('branchstatus', models.CharField(blank=True, choices=[('A', 'Active')], db_column='BranchStatus', max_length=1, null=True, verbose_name='Status')),
                ('pscounttype', models.CharField(blank=True, db_column='PSCountType', max_length=1, null=True, verbose_name='ps count type')),
                ('pscountperiod', models.CharField(blank=True, db_column='PSCountPeriod', max_length=1, null=True, verbose_name='ps count period')),
                ('pscountmodules', models.CharField(blank=True, db_column='PSCountModules', max_length=1, null=True, verbose_name='ps count modules')),
                ('pricingpolicy', models.CharField(blank=True, db_column='PricingPolicy', max_length=4, null=True, verbose_name='pricing Policy')),
                ('imcounttype', models.CharField(blank=True, db_column='IMCountType', max_length=1, null=True, verbose_name='im count type')),
                ('imcountperiod', models.CharField(blank=True, db_column='IMCountPeriod', max_length=1, null=True, verbose_name='im count period')),
                ('imcountmodules', models.CharField(blank=True, db_column='IMCountModules', max_length=1, null=True, verbose_name='im count modules')),
                ('i', models.CharField(blank=True, max_length=1, null=True, verbose_name='im count modules')),
                ('magdy', models.TextField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Branch',
                'managed': True,
                'unique_together': {('companycode', 'branchcode')},
            },
        ),
    ]
